/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreatePasswordRouteImport } from './routes/create-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated.students.$id'
import { Route as AuthenticatedStudentSavedRouteImport } from './routes/_authenticated.student.saved'
import { Route as AuthenticatedStudentProgressRouteImport } from './routes/_authenticated.student.progress'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated.student.profile'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated.student.applications'
import { Route as AuthenticatedCompanyProfileRouteImport } from './routes/_authenticated.company.profile'
import { Route as AuthenticatedCompanyPostsRouteImport } from './routes/_authenticated.company.posts'
import { Route as AuthenticatedCompanyApplicationsRouteImport } from './routes/_authenticated.company.applications'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'
import { Route as AuthenticatedStudentJobsIndexRouteImport } from './routes/_authenticated.student.jobs.index'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated.admin.students.index'
import { Route as AuthenticatedAdminPostsIndexRouteImport } from './routes/_authenticated.admin.posts.index'
import { Route as AuthenticatedAdminCompaniesIndexRouteImport } from './routes/_authenticated.admin.companies.index'
import { Route as AuthenticatedAdminStudentsIdRouteImport } from './routes/_authenticated.admin.students.$id'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated.admin.posts.$id'
import { Route as AuthenticatedAdminCompaniesIdRouteImport } from './routes/_authenticated.admin.companies.$id'
import { Route as AuthenticatedStudentJobsIdApplyRouteImport } from './routes/_authenticated.student.jobs.$id.apply'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePasswordRoute = CreatePasswordRouteImport.update({
  id: '/create-password',
  path: '/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentSavedRoute =
  AuthenticatedStudentSavedRouteImport.update({
    id: '/student/saved',
    path: '/student/saved',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentProgressRoute =
  AuthenticatedStudentProgressRouteImport.update({
    id: '/student/progress',
    path: '/student/progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/student/applications',
    path: '/student/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyProfileRoute =
  AuthenticatedCompanyProfileRouteImport.update({
    id: '/company/profile',
    path: '/company/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyPostsRoute =
  AuthenticatedCompanyPostsRouteImport.update({
    id: '/company/posts',
    path: '/company/posts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyApplicationsRoute =
  AuthenticatedCompanyApplicationsRouteImport.update({
    id: '/company/applications',
    path: '/company/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentJobsIndexRoute =
  AuthenticatedStudentJobsIndexRouteImport.update({
    id: '/student/jobs/',
    path: '/student/jobs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/admin/students/',
    path: '/admin/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPostsIndexRoute =
  AuthenticatedAdminPostsIndexRouteImport.update({
    id: '/admin/posts/',
    path: '/admin/posts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCompaniesIndexRoute =
  AuthenticatedAdminCompaniesIndexRouteImport.update({
    id: '/admin/companies/',
    path: '/admin/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStudentsIdRoute =
  AuthenticatedAdminStudentsIdRouteImport.update({
    id: '/admin/students/$id',
    path: '/admin/students/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/admin/posts/$id',
    path: '/admin/posts/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCompaniesIdRoute =
  AuthenticatedAdminCompaniesIdRouteImport.update({
    id: '/admin/companies/$id',
    path: '/admin/companies/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentJobsIdApplyRoute =
  AuthenticatedStudentJobsIdApplyRouteImport.update({
    id: '/student/jobs/$id/apply',
    path: '/student/jobs/$id/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-password': typeof CreatePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/company/applications': typeof AuthenticatedCompanyApplicationsRoute
  '/company/posts': typeof AuthenticatedCompanyPostsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/student/saved': typeof AuthenticatedStudentSavedRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
  '/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
  '/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/student/jobs/': typeof AuthenticatedStudentJobsIndexRoute
  '/student/jobs/$id/apply': typeof AuthenticatedStudentJobsIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-password': typeof CreatePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/company/applications': typeof AuthenticatedCompanyApplicationsRoute
  '/company/posts': typeof AuthenticatedCompanyPostsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/student/saved': typeof AuthenticatedStudentSavedRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesIndexRoute
  '/admin/posts': typeof AuthenticatedAdminPostsIndexRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/student/jobs': typeof AuthenticatedStudentJobsIndexRoute
  '/student/jobs/$id/apply': typeof AuthenticatedStudentJobsIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/create-password': typeof CreatePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/company/applications': typeof AuthenticatedCompanyApplicationsRoute
  '/_authenticated/company/posts': typeof AuthenticatedCompanyPostsRoute
  '/_authenticated/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/progress': typeof AuthenticatedStudentProgressRoute
  '/_authenticated/student/saved': typeof AuthenticatedStudentSavedRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/_authenticated/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/_authenticated/admin/companies/': typeof AuthenticatedAdminCompaniesIndexRoute
  '/_authenticated/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
  '/_authenticated/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/_authenticated/student/jobs/': typeof AuthenticatedStudentJobsIndexRoute
  '/_authenticated/student/jobs/$id/apply': typeof AuthenticatedStudentJobsIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/admin/analytics'
    | '/company/applications'
    | '/company/posts'
    | '/company/profile'
    | '/student/applications'
    | '/student/profile'
    | '/student/progress'
    | '/student/saved'
    | '/students/$id'
    | '/admin/companies/$id'
    | '/admin/posts/$id'
    | '/admin/students/$id'
    | '/admin/companies/'
    | '/admin/posts/'
    | '/admin/students/'
    | '/student/jobs/'
    | '/student/jobs/$id/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/admin/analytics'
    | '/company/applications'
    | '/company/posts'
    | '/company/profile'
    | '/student/applications'
    | '/student/profile'
    | '/student/progress'
    | '/student/saved'
    | '/students/$id'
    | '/admin/companies/$id'
    | '/admin/posts/$id'
    | '/admin/students/$id'
    | '/admin/companies'
    | '/admin/posts'
    | '/admin/students'
    | '/student/jobs'
    | '/student/jobs/$id/apply'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/create-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/company/applications'
    | '/_authenticated/company/posts'
    | '/_authenticated/company/profile'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/progress'
    | '/_authenticated/student/saved'
    | '/_authenticated/students/$id'
    | '/_authenticated/admin/companies/$id'
    | '/_authenticated/admin/posts/$id'
    | '/_authenticated/admin/students/$id'
    | '/_authenticated/admin/companies/'
    | '/_authenticated/admin/posts/'
    | '/_authenticated/admin/students/'
    | '/_authenticated/student/jobs/'
    | '/_authenticated/student/jobs/$id/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreatePasswordRoute: typeof CreatePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-password': {
      id: '/create-password'
      path: '/create-password'
      fullPath: '/create-password'
      preLoaderRoute: typeof CreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/saved': {
      id: '/_authenticated/student/saved'
      path: '/student/saved'
      fullPath: '/student/saved'
      preLoaderRoute: typeof AuthenticatedStudentSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/progress': {
      id: '/_authenticated/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof AuthenticatedStudentProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/profile': {
      id: '/_authenticated/company/profile'
      path: '/company/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof AuthenticatedCompanyProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/posts': {
      id: '/_authenticated/company/posts'
      path: '/company/posts'
      fullPath: '/company/posts'
      preLoaderRoute: typeof AuthenticatedCompanyPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/applications': {
      id: '/_authenticated/company/applications'
      path: '/company/applications'
      fullPath: '/company/applications'
      preLoaderRoute: typeof AuthenticatedCompanyApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/jobs/': {
      id: '/_authenticated/student/jobs/'
      path: '/student/jobs'
      fullPath: '/student/jobs/'
      preLoaderRoute: typeof AuthenticatedStudentJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students/': {
      id: '/_authenticated/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/posts/': {
      id: '/_authenticated/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AuthenticatedAdminPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/companies/': {
      id: '/_authenticated/admin/companies/'
      path: '/admin/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students/$id': {
      id: '/_authenticated/admin/students/$id'
      path: '/admin/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/admin/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/companies/$id': {
      id: '/_authenticated/admin/companies/$id'
      path: '/admin/companies/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/jobs/$id/apply': {
      id: '/_authenticated/student/jobs/$id/apply'
      path: '/student/jobs/$id/apply'
      fullPath: '/student/jobs/$id/apply'
      preLoaderRoute: typeof AuthenticatedStudentJobsIdApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedCompanyApplicationsRoute: typeof AuthenticatedCompanyApplicationsRoute
  AuthenticatedCompanyPostsRoute: typeof AuthenticatedCompanyPostsRoute
  AuthenticatedCompanyProfileRoute: typeof AuthenticatedCompanyProfileRoute
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentProgressRoute: typeof AuthenticatedStudentProgressRoute
  AuthenticatedStudentSavedRoute: typeof AuthenticatedStudentSavedRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedAdminCompaniesIdRoute: typeof AuthenticatedAdminCompaniesIdRoute
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
  AuthenticatedAdminStudentsIdRoute: typeof AuthenticatedAdminStudentsIdRoute
  AuthenticatedAdminCompaniesIndexRoute: typeof AuthenticatedAdminCompaniesIndexRoute
  AuthenticatedAdminPostsIndexRoute: typeof AuthenticatedAdminPostsIndexRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
  AuthenticatedStudentJobsIndexRoute: typeof AuthenticatedStudentJobsIndexRoute
  AuthenticatedStudentJobsIdApplyRoute: typeof AuthenticatedStudentJobsIdApplyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedCompanyApplicationsRoute: AuthenticatedCompanyApplicationsRoute,
  AuthenticatedCompanyPostsRoute: AuthenticatedCompanyPostsRoute,
  AuthenticatedCompanyProfileRoute: AuthenticatedCompanyProfileRoute,
  AuthenticatedStudentApplicationsRoute: AuthenticatedStudentApplicationsRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentProgressRoute: AuthenticatedStudentProgressRoute,
  AuthenticatedStudentSavedRoute: AuthenticatedStudentSavedRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedAdminCompaniesIdRoute: AuthenticatedAdminCompaniesIdRoute,
  AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
  AuthenticatedAdminStudentsIdRoute: AuthenticatedAdminStudentsIdRoute,
  AuthenticatedAdminCompaniesIndexRoute: AuthenticatedAdminCompaniesIndexRoute,
  AuthenticatedAdminPostsIndexRoute: AuthenticatedAdminPostsIndexRoute,
  AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
  AuthenticatedStudentJobsIndexRoute: AuthenticatedStudentJobsIndexRoute,
  AuthenticatedStudentJobsIdApplyRoute: AuthenticatedStudentJobsIdApplyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreatePasswordRoute: CreatePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
